name: Hidden Street
description: Chris Thi's Blog
meta_description: "My blog."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://cthi.github.io'


# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Chris Thi'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
